# Generated by Django 4.2.30 on 2026-05-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("on_hold", "暂停"),
                            ("archived", "已归档"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "事项",
                "verbose_name_plural": "事项",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="步骤序号")),
                ("content", models.TextField(verbose_name="步骤内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("blocked", "受阻"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="结果记录")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "节点步骤",
                "verbose_name_plural": "节点步骤",
                "ordering": ["node", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="TimelineNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="序号")),
                ("title", models.CharField(max_length=200, verbose_name="节点标题")),
                ("summary", models.TextField(blank=True, verbose_name="概要")),
                ("node_date", models.DateField(verbose_name="节点日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="XMGJ_app.item",
                        verbose_name="所属事项",
                    ),
                ),
            ],
            options={
                "verbose_name": "时间轴节点",
                "verbose_name_plural": "时间轴节点",
                "ordering": ["item", "node_date", "sequence"],
                "unique_together": {("item", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="NodeStepFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("attachment", "附件"), ("image", "图片")],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="step_files/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="XMGJ_app.nodestep",
                        verbose_name="所属步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "步骤文件",
                "verbose_name_plural": "步骤文件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="nodestep",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="XMGJ_app.timelinenode",
                verbose_name="所属节点",
            ),
        ),
        migrations.CreateModel(
            name="NodeAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="操作内容")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("complete", "完成"),
                            ("problem", "问题"),
                        ],
                        default="update",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="XMGJ_app.timelinenode",
                        verbose_name="所属节点",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作记录",
                "verbose_name_plural": "操作记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="nodestep",
            unique_together={("node", "sequence")},
        ),
    ]
