# Generated by Django 4.2.30 on 2026-05-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XMGJ_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodestep",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="步骤标题"
            ),
        ),
    ]
